support magic ip so statsd can be used within container network

diff --git a/system/netdata-lsb.in b/system/netdata-lsb.in
--- a/system/netdata-lsb.in
+++ b/system/netdata-lsb.in
@@ -46,6 +46,8 @@ service_start() {
 	fi
 	
 	log_daemon_msg "Starting real-time performance monitoring" "netdata"
+	# support magic ip so statsd can be used within container network
+	ip link add netdata type dummy || echo "inf already present"; ip addr add 169.254.254.254/32 dev netdata || echo "ip addr already present" 
 	start_daemon -p $PIDFILE $DAEMON_PATH/$DAEMON $DAEMONOPTS
 	RETVAL=$?
 	log_end_msg $RETVAL
@@ -61,6 +63,7 @@ service_stop() {
 	if [ $RETVAL -eq 0 ]; then
 		rm -f ${PIDFILE}
 	fi
+	ip addr del 169.254.254.254/32 dev netdata || echo "unable clean up if addr" ; ip link del netdata || echo "unable clean up vinf"
 	return $RETVAL
 }
 
